[package]
name = "phireader"
version = "0.1.6"
description = "PhiReader desktop shell"
authors = ["PhiReader"]
license = "MIT"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
keyring = { version = "3", features = ["windows-native"] }
reqwest = { version = "0.13.1", features = ["json"] }
tauri-plugin-process = "2"
tauri-plugin-opener = "2"
tauri-plugin-updater = "2"

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]
